
spring:
  jpa:
    hibernate:
      # naming:
      #   physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://ecomarket-ecopoint-db.cgcyiu667p2z.ap-northeast-2.rds.amazonaws.com:3306/ecopoint_db?characterEncoding=UTF-8&serverTimezone=UTC&autoReconnect=true
    username: admin
    password: admin123
    driverClassName: com.mysql.cj.jdbc.Driver    
  # datasource:
  #   url: jdbc:mysql://localhost:3306/scott?characterEncoding=UTF-8&serverTimezone=UTC&autoReconnect=true
  #   username: root
  #   password: 1234
  #   driverClassName: com.mysql.cj.jdbc.Driver

---

server:
  port: 8084

spring:
  profiles: default
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:29092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: EcoPoint
          destination: ecomarket
          contentType: application/json
        event-out:
          destination: ecomarket
          contentType: application/json

logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug

---


spring:
  profiles: docker
  cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka.kafka.svc.cluster.local:9092 
          # brokers: kafka:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: EcoPoint
          destination: ecomarket
          contentType: application/json
        event-out:
          destination: ecomarket
          contentType: application/json
