apiVersion: v1
kind: Service
metadata:
  name: ecopoint-svc
  namespace: ecomarket
  labels:
    app: ecopoint
spec:
  ports:
    - port: 80
      targetPort: 8084
  selector:
    app: ecopoint
  type: NodePort
